[package]
name = "generalized-dex-runtime"
version = "0.0.0"
authors = []
edition = "2018"

[dependencies]
pallet-exchange = { path = "../pallets/exchange", version = "0.0.0" }
sp-api = { version = "2.0.0" }
sp-runtime = { version = "2.0.0" }
