[package]
authors = []
edition = "2018"
license = ""
name = "pallet-exchange"
repository = ""
version = "0.0.0"

[dependencies]
frame-support = { version = "2.0.0" }
frame-system = { version = "2.0.0" }
